### ISSUE TITLE
Implementing scan server in python

### ISSUE THREAD

**Issue by Krishna-de** [jence/j4210u-app#18]
I brought one of you are UHF reader/writer. Works good. We are using device via Python Api. how can I implement Scan server, merge, clean functions in my python API ? At the moment they are only implemented in Windows GUI

**Comment by jence** [comment]
Hello Krishna,
Most people use Java, so we implemented most features in Java. Those who use Python implement their own code and didn't ask us to modify the GUI. But you asked us to implement Scan Server, Merge and Clean buttons and we will do that. These are mostly GUI functionality, we will try to add these within the next week. Once they are added, we will send you a note and you can get the code by downloading (or cloning) the latest code. Thank you.

Regards,
Mansur

**Comment by jence** [comment]
We have added Scan Server, Merge and Clear into the Python code. You may test and report any bugs. Thank you.
Regards,
Mansur
