### ISSUE TITLE
Data Flooding optimization

### ISSUE THREAD

**Issue by Krishna-de** [jence/j4210u-app#19]
Hi I have lot RFID tags comes in roll. How do I find out nearest tag from J4210 reader?. I tried with RSSI with lowest value but it is not stable. Could you point me to right direction?

**Comment by jence** [comment]
RSSI is not always reliable. What you can do is to reduce the power of the reader by going to INFO tab. 26dbm is the highest power. Set it to half of that to start with. If you can read any tag, then you know those are closer. If no cards read, increase the power and scan again. RSSI combined with power, you can find the closest tag. But, you need to build an algorithm from this idea. We don't have any algorithm yet.
-Mansur

**Comment by Krishna-de** [comment]
Thank you so much for the support and info
