### ISSUE TITLE
How do I write strings like LK in word index? I tried to convert this to 4c4b but it writes as it is in EPC when scan the tag it shows 4c4b instead of LK in EPC

### ISSUE THREAD

**Issue by Krishna-de** [jence/j4210u-app#20]
newepc0 = b'\x4c\x4b'
        print("Changing the EPC first two bytes to ", f.Bytes2Hex(newepc0))
        # our first index is 0
        ret = f.WriteEpcWord(sr.EPC, newepc0, 0)
        assert ret == True
I tested with this snippet from test script

**Comment by jence** [comment]
EPC is always in HEX. The inventory table displays everything in HEX currently. But we can add an option to display the EPC as ASCII, if you so desire. Do you want this?
Regards,
Mansur.

**Comment by Krishna-de** [comment]
@jence  Thank for the reply, at the moment not required.
