### ISSUE TITLE
Convert strings for example epc(LK-14589) to Bytes for writeEPCword method how do I achieve this in python API?

### ISSUE THREAD

**Issue by Krishna-de** [jence/j4210u-app#22]

**Comment by jence** [comment]
call bytes.fromhex(hex)
We have added a method in the j421xlib.py called Hex2Bytes() to do that. Get the source code j421xlib.py.
Regards,
Mansur

**Comment by Krishna-de** [comment]
"LK-14589" is not Hex string, Hex2Bytes() does not work since it accepts hex strings, mine is pure ascii string. I tried many different variations try to convert this but none of my approaches work. could you provide me code snippet to convert ascii string to 2 byte EPC word for WriteEPCWord()

**Comment by jence** [comment]
I think you want a method to write a ASCII document as bytes. We will
provide that.

**Comment by Krishna-de** [comment]
Thanks would be great

**Comment by jence** [comment]
Two new methods have been added:
Ascii2Bytes()
Bytes2Ascii()
These will do the conversions from one type to another.
Regards,
Mansur
