### ISSUE TITLE
Spinning wheel in GUI on MacOS w/ Apple Silicon

### ISSUE THREAD

**Issue by buxy442** [jence/j4210u-app#27]
I really look forward to using the device. I was able to download and execute the Jence Uhf App.  When plugging in the desktop reader (I have the one with the GPIO and UART ports), and htiting refresh, I see tty.usbmodem1101.  The problem happens after I hit connect.  I just get the Mac Spinning Wheel.  I've tried this on a mac with intel and another mac with the M1 chip.  The same problem is happening on both.  

In my terminal is says 
Effective port: /dev/tty.usbmodem1101
Hardware is Little Endian

And then just the spinning wheel in the gui

Any insights?

**Comment by jence** [comment]
I will look into the issue. Have you tried older release? Sometimes older
release work.

**Comment by buxy442** [comment]
Thank you. The older release worked.
